### ISSUE TITLE
Website Server

### ISSUE THREAD

**Issue by MurderAxolotl** [SheepTester/primitive-cloud-server#13]
I've tried several ways to host the primitive cloud server on a website (such as Github Pages, Netlify, and Vercel), but when I try to connect from my project, the cloud variables do not work (the server isn't running, I think).

I can't set up port forwarding on my router, and I want my server to be publicly accessible. Do you have any suggestions on what I could use to do this?
Any help would be greatly appreciated, thanks in advance.

**Comment by SheepTester** [comment]
I'm not familiar with other options, but I know that it won't work on GitHub Pages since GitHub Pages is only a static site host, so it doesn't support backends. Maybe you might be able to use [Replit](https://replit.com/), though I'm not familiar with that either

**Comment by MurderAxolotl** [comment]
Okay, thank you

**Comment by Dashbloxx** [comment]
I've tried replit and the scratch game gets paused when it tries to change a cloud variable. The scratch game sends this message to the console:

DOMException {
  stack: 'Error: Failed to construct \'WebSocket\': The URL\'s scheme must be either \'ws\' or \'wss\'. \'https\' is not allowed.\n    at CloudProvider._openConnection (https://6af63449-4ae6-4d55-b6d3-6803ee32771b.id.repl.co/:551:18)\n    at new CloudProvider (https://6af63449-4ae6-4d55-b6d3-6803ee32771b.id.repl.co/:545:12)\n    at window.init (https://6af63449-4ae6-4d55-b6d3-6803ee32771b.id.repl.co/:1346:25)' }

**Comment by SheepTester** [comment]
I guess you gave a https:// URL instead of a wss:// URL for the cloud server URL

**Comment by Dashbloxx** [comment]
I was coming here to github about to make a new comment saying that the fix was to change the https:// to ws://, but it  looks like you responded with the solution before I could. Thank you for the answer though.

**Comment by Dashbloxx** [comment]
> I was coming here to github about to make a new comment saying that the fix was to change the https:// to ws://, but it looks like you responded with the solution before I could. Thank you for the answer though.

I'm going to fix another thing that I said: if you're using repl.it, use wss:// instead of ws://

**Comment by SparkScratch-P** [comment]
Can anyone guide me on exactly how to set up my universals server without keeping my PC o, like on Heroku, or replit??
