### ISSUE TITLE
(Question) Is there a way to run this on the cloud?

### ISSUE THREAD

**Issue by TheShovel** [SheepTester/primitive-cloud-server#16]
I tried to run this on heroku, but it shuts it down with error exit status 143 (Stopping all processes with SIGTERM).
 Is there other free way to do this? I don't wanna have a constantly running pc in my room to run my game server.
 
Thanks again for your time!

**Comment by TheShovel** [comment]
Never mind, found it out myself. Using heroku.

**Comment by infernostars** [comment]
How did you do this? I also want to set up my own server, so it'd be nice if I knew how

**Comment by infernostars** [comment]
@cataghg 
bump, if you have time.

**Comment by TheShovel** [comment]
just google how to set up a herku app, it's really easy.

**Comment by infernostars** [comment]
alright thanks
