### ISSUE TITLE
I am facing 3 problems while setting up  a primitive cloud server.

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/primitive-cloud-server#3]
I am facing the following problems while setting up a primitive cloud server.

- When we r giving the code in Comand Prompt, should the Command Prompt be the one of the previously existing, or the Node.js window? Pls, Help me out. 

- Also When We r giving `git clone https://github.com/SheepTester/primitive-cloud-server.git`, the `clone` is said to be an unexpected syntax error.

- And... What to do with the code after typing in the prompt. How to save? or what else to do?

**Comment by SheepTester** [comment]
If closing the Node.js winodw stops the server (i.e. command prompt then asks for the next command), you shouldn't close the Node.js window

If `clone` is giving you an unexpected syntax error, it might be because you're running this in the Node.js command prompt, not your computer's command prompt (such as cmd.exe, PowerShell, or Git Bash).

Once the server is running, it will automatically save cloud variables to a file. You can just keep the window open and running; there's nothing else to do

**Comment by SparkScratch-P** [comment]
I didn't understand the last thing.
I type the given code in Cmd. Then If I want to play the game, I need to keep the cmd window as it was while typing and run the game? or can I close cmd once typed and  whenever my PC is connected to the internet, it will work as a server overcloud? or should I type the given thing every time in cmd while playing the game each time?

**Comment by SparkScratch-P** [comment]
I will be using Windows Powershell  then

**Comment by SparkScratch-P** [comment]
Whether it be cmd.exe or Powershell, at first it's asking for a location like:
`C:/Users/Admin>`
Should I specify a file path there? and start my code from the next line?

**Comment by SheepTester** [comment]
> I didn't understand the last thing.
> I type the given code in Cmd. Then If I want to play the game, I need to keep the cmd window as it was while typing and run the game? or can I close cmd once typed and whenever my PC is connected to the internet, it will work as a server overcloud? or should I type the given thing every time in cmd while playing the game each time?

You need to keep the cmd window open. If you close it, the server will stop working. You do not need to type the command again as long as it stays open.



> Whether it be cmd.exe or Powershell, at first it's asking for a location like:
> `C:/Users/Admin>`
> Should I specify a file path there? and start my code from the next line?

You should use `cd` to specify the file path. For example, if the folder with the server is at C:\Users\yourname\Documents\primitive-cloud-server (which you can copy from Windows Explorer), you can run

```batch
cd C:\Users\yourname\Documents\primitive-cloud-server
```

After that, you can start the code on the next line.

**Comment by SparkScratch-P** [comment]
Hi Sean, hope u r doing well, speaking after really long!

I just need some help. Can this cloud variable store only numbers, or some special characters as well? Pls, help.

Thank you.

**Comment by SheepTester** [comment]
It doesn't enforce Scratch's cloud limits, so it accepts any string

**Comment by SparkScratch-P** [comment]
Thanks a lot bro!~~
