### ISSUE TITLE
How would I connect globally

### ISSUE THREAD

**Issue by CodeDelta247** [SheepTester/primitive-cloud-server#4]
Turbowarp has a setting that allows you to choose a cloud server would I put (the device with the server's ipv4):3000

**Comment by SheepTester** [comment]
Yes, but you'd also have to make sure your router has port forwarding set up to forward port 3000 to the computer running the cloud server so that people outside your network can access it. Also make sure the IP address is the public IP address (ie it doesn't start with 192.168.)

**Comment by CodeDelta247** [comment]
Where can I check the variables on the pc running the server? And thanks.

**Comment by SheepTester** [comment]
I believe the server stores the cloud variables in a JSON file in a `cloud-vars` folder which the server creates.
