### ISSUE TITLE
How do you make this public?

### ISSUE THREAD

**Issue by spacebytee** [SheepTester/primitive-cloud-server#6]
I'm making a rhythm game, and I'm trying to plan all this stuff in advance so I can make a good game with just scratch, I need to know how I can make the server public without port forwarding, is there any type of free server we can use, and how? Like I know you can get free mysql databases, what type of dtabase do I need for this? Is it a normal web server for web hosting?

**Comment by SheepTester** [comment]
This primitive cloud server, being primitive, doesn't use any kind of database; it just writes to a JSON file. It's just a normal web (HTTP and WebSocket) server

However, I don't know of any [free](https://fastgood.cheap/) server host

**Comment by spacebytee** [comment]
So all I need is a json file stored on a server? Maybe I could use github pages or something and have it get the file as a page if that's how this works? You think you would mind maybe making a tutorial on how to do it with a server instead of on your local pc?

**Comment by spacebytee** [comment]
I just thought about it, and  I remembered how I did minecraft servers, I used ngrok to port forward my server without actually port forwarding so people could join, however the port for ngrok updates everytime you restart it, so I would need to update my project, so what if I used a redirect that redirect to my ngrok server, that I can manually change without updating the project.

**Comment by SheepTester** [comment]
This server automatically creates the JSON file; you don't need to create it yourself.

I can't make a tutorial for hosting the server on a server host because there's a large variety, so one tutorial can't encapsulate all of them, and I'm not familiar with any of them.

A redirect to your ngrok server might work

**Comment by spacebytee** [comment]
Wait, so all I need is the host, I don't need to do anything with it manually except to create the server? Because if thats so, I would really only need a web socket host and that's it, right?

**Comment by SheepTester** [comment]
Think so

**Comment by therealxouzouris** [comment]
So you don't have to port-forward your router if you use ngrok? Is it safer than port forwarding?

**Comment by SheepTester** [comment]
Perhaps not, though I am not very well versed in networking, unfortunately
